/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sem08;

import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

/**
 *
 * @author Laboratorio
 */
public class MenuVentas extends javax.swing.JFrame {
    public Menu padre;
    
    /**
     * Creates new form MenuVentas
     */
    public MenuVentas() {
        initComponents();
    }
    
    public MenuVentas(Menu menu){
        this.padre = menu;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuVentasLabel = new javax.swing.JLabel();
        listaVentasButton = new javax.swing.JButton();
        listaVentasSubcontenedor = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        ventasJList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        menuVentasLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuVentasLabel.setText("Menu Ventas");

        listaVentasButton.setText("Lista Ventas");
        listaVentasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaVentasButtonActionPerformed(evt);
            }
        });

        ventasJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ventasJList);

        listaVentasSubcontenedor.addTab("tab1", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listaVentasSubcontenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaVentasButton)
                    .addComponent(menuVentasLabel))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuVentasLabel)
                .addGap(18, 18, 18)
                .addComponent(listaVentasButton)
                .addGap(18, 18, 18)
                .addComponent(listaVentasSubcontenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.padre.setVisible(true);
        
    }//GEN-LAST:event_formWindowClosing

    private void listaVentasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaVentasButtonActionPerformed
        Vector<String> dataset = new Vector<String>();
        
        dataset.add("590.00");
        dataset.add("591.00");
        dataset.add("594.00");
        dataset.add("290.00");
        dataset.add("490.00");
        dataset.add("950.00");
        dataset.add("690.00");
        dataset.add("1290.00");        
        
        this.ventasJList.setListData(dataset);
    }//GEN-LAST:event_listaVentasButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listaVentasButton;
    private javax.swing.JTabbedPane listaVentasSubcontenedor;
    private javax.swing.JLabel menuVentasLabel;
    private javax.swing.JList<String> ventasJList;
    // End of variables declaration//GEN-END:variables
}
